azs:
- name: z1
compilation:
  az: z1
  network: concourse
  workers: 3
disk_types:
- disk_size: 10240
  name: db
- disk_size: 2048
  name: minio
networks:
- name: concourse
vm_types:
- name: concourse
  network: concourse
